/**
 * MQTT service module
 * @param serviceName (string) Name of the service
 * @param mqttConfig  (object) {
 *   handle: 'mqtt://example.com:123',
 *   username: 'Billy',
 *   password: 'VerySecretThingy'
 *   domain: 'smoothmining'
 * }
 */

/**
 * Dependencies
 */
var EventEmitter = require('events').EventEmitter;
var mqtt = require('mqtt');

function MQTTService(serviceName, mqttConfig) {
  EventEmitter.call(this);
  var _self = this;

  this.serviceName = serviceName;

  // The domain topic as prefix for all other topics
  this.domainTopic = mqttConfig.domain + (mqttConfig.domain.substr(mqttConfig.domain.length-1) == '/' ? '' : '/'); // Add trailing slash if not there
  
  // Topic used to publihs data about the service script itself
  this.systemTopic = this.domainTopic + 'services/' + this.serviceName + '/';

  // Topic used to publish data generated by the service script
  this.serviceTopic = this.domainTopic + this.serviceName + '/';

  // Connect to the MQTT broker
  this.broker = mqtt.connect(mqttConfig.handle, {
    username: mqttConfig.username,
    password: mqttConfig.password,
    
    // Let broker update service status to `stopped` on disconnect
    will: {
      topic: _self.systemTopic + 'status',
      payload: 'stopped',
      qos: 2,
      retain: true
    }
  })
  .on('connect', function () {
    console.log('MQTT connected');

    // Update broker status to `running` on connect
    this.publish(_self.systemTopic + 'status', 'running', {qos: 2, retain: true});

    // Subscribe
    this.subscribe(_self.systemTopic + '#');
    this.subscribe(_self.serviceTopic + '#');
  })
  .on('message', function (topic, message) {
    // Remove domain topic
    var topic = topic.replace(_self.domainTopic, '');

    // Passthrough original message
    _self.emit('message', topic, message.toString());

    // Emit topic event to allow for listening to a specific topic
    _self.emit(topic, message.toString());
    
    // Check whether the message is command for the service to do something
    if(topic.indexOf(_self.systemTopic) != -1) {
      _self.emit('command', message);
    }
  });
}
  MQTTService.prototype = Object.create(EventEmitter.prototype);

  /**
   * Publishes a message containing data generated by the service
   * Usage:
   * .publish('sensor1value', 'high');
   * Will publish:
   * /myDomain/myServiceName/sensor1value `high`
   */
  MQTTService.prototype.publish = function(topic, message) {
    this.broker.publish(this.serviceTopic + topic, message, {qos: 2, retain: true});
  }

  /**
   * Add topic to listen to
   */
  MQTTService.prototype.subscribe = function(topic) {
    this.broker.subscribe(this.domainTopic + topic);
  }

module.exports = MQTTService;